
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analyzers;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MINUS = 10;
  public static final int RKS = 6;
  public static final int UMINUS = 15;
  public static final int RK = 8;
  public static final int NUMBER = 13;
  public static final int MULT = 11;
  public static final int LK = 7;
  public static final int LPAR = 3;
  public static final int STRING = 14;
  public static final int PLUS = 9;
  public static final int EOF = 0;
  public static final int DIV = 12;
  public static final int RW_CALCULATE = 16;
  public static final int error = 1;
  public static final int SEMICOLON = 2;
  public static final int RPAR = 4;
  public static final int LKS = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMICOLON",
  "LPAR",
  "RPAR",
  "LKS",
  "RKS",
  "LK",
  "RK",
  "PLUS",
  "MINUS",
  "MULT",
  "DIV",
  "NUMBER",
  "STRING",
  "UMINUS",
  "RW_CALCULATE"
  };
}

